---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
  labels:
    app: telegram-bot
spec:
  selector:
    app: telegram-bot
  ports:
    - protocol: TCP
      port: 80        # Puerto expuesto por el Service
      targetPort: 80  # Puerto dentro del contenedor
