---
apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

commonLabels:
  env: dev
  app.kubernetes.io/instance: telegram-bot
  app.kubernetes.io/module: pw3
  app.kubernetes.io/name: telegram-bot

images:
- name: telegram-bot
  newName: ghcr.io/karencilla-unlam/grupo12-microservicios-y-docker
  newTag: latest

resources:
  - bot-deployment.yaml
#  - bot-sealed-secret.yaml -- Esto lo generó local cada uno, ya que al ser un minikube diferente por máquina, cambia el yaml resultante
  - bot-service.yaml

namespace: chatbot-dev
