---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: github-runner
          image: ghcr.io/actions/runner:latest 
          env:
            - name: RUNNER_NAME
              value: "minikube-runner"
            - name: RUNNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner-secret
                  key: token
            - name: RUNNER_REPOSITORY_URL
              value: "https://github.com/karencilla-unlam/grupo12-microservicios-y-docker"
          volumeMounts:
            - name: runner-volume
              mountPath: /runner
      volumes:
        - name: runner-volume
          emptyDir: {}
