
CREATE TABLE Respuestas;
CREATE TABLE Consultas;

TRUNCATE TABLE Consultas;
TRUNCATE TABLE Respuestas;

DROP TABLE Respuestas;
DROP TABLE Consultas;




-- Insert Questions
INSERT INTO Consultas VALUES
(N'Cuando la escuela me entrega el título o analítico del nivel secundario, ¿debo hacer algo antes de presentarlo en la Universidad?'),
(N'¿Qué requisitos son necesarios para realizar la inscripción al Curso de ingreso?'),
(N'¿Puede otra persona realizar la inscripción por mí?'),
(N'Si el día de la inscripción me falta alguna documentación, ¿la puedo alcanzar en otro momento?'),
(N'¿Con qué me inscribo si mi DNI está en trámite? ¿Me sirve el DNI de menor de edad?'),
(N'¿Me puedo inscribir con la denuncia de robo y/o extravío?'),
(N'¿Qué es el formulario de preinscripción y cuándo se habilita?'),
(N'Si tengo materias aprobadas en otra Universidad ¿me las reconocen?'),
(N'¿Puedo hacer el Curso de Ingreso adeudando materias del secundario?'),
(N'Si todavía no estoy seguro de la carrera a elegir ¿existe algún test vocacional que pueda realizar en la Universidad?'),
(N'Si tengo el mejor promedio del colegio, ¿tengo que hacer el Curso de Ingreso?'),
(N'Si soy graduado de otra Universidad, ¿debo hacer el Curso de Ingreso? ¿Cuáles son los requisitos?'),
(N'El Curso de Ingreso, ¿se puede realizar a distancia?'),
(N'¿Cuántas faltas se puede tener por materia?'),
(N'¿Me puedo cambiar de turno o de días en el Curso de ingreso?'),
(N'¿Puedo realizar el Curso de Ingreso para cualquiera de las carreras de la Universidad en la Segunda instancia?'),
(N'¿El examen se rinde en la misma aula donde curso?'),
(N'¿Cuánto tiempo se otorga para realizar el examen?'),
(N'¿Tengo que llevar algo para rendir los exámenes?'),
(N'¿Me puedo cambiar de aula para rendir el examen?'),
(N'Si no puedo asistir al examen, ¿Puedo rendir en otra fecha?'),
(N'¿Qué es la constancia de asistencia a exámen? ¿Cómo se tramita?'),
(N'¿Con que universidades de Alemania tiene convenio la UNLaM?'),
(N'¿Con que universidades de Austria tiene convenio la UNLaM?'),
(N'¿Con que universidades de Bélgica tiene convenio la UNLaM?'),
(N'¿Con que universidades de Bosnia & Herzegovina tiene convenio la UNLaM?'),
(N'¿Con que universidades de Brasil tiene convenio la UNLaM?'),
(N'¿Con que universidades de Canadá tiene convenio la UNLaM?'),
(N'¿Con que universidades de Colombia tiene convenio la UNLaM?'),
(N'¿Con que universidades de Costa Rica tiene convenio la UNLaM?'),
(N'¿Con que universidades de Croacia tiene convenio la UNLaM?'),
(N'¿Con que universidades de Ecuador tiene convenio la UNLaM?'),
(N'¿Con que universidades de El Salvador tiene convenio la UNLaM?'),
(N'¿Con que universidades de Eslovaquia tiene convenio la UNLaM?'),
(N'¿Con que universidades de España tiene convenio la UNLaM?'),
(N'¿Con que universidades de Estados Unidos tiene convenio la UNLaM?'),
(N'¿Con que universidades de India tiene convenio la UNLaM?'),
(N'¿Con que universidades de Francia tiene convenio la UNLaM?'),
(N'¿Con que universidades de Hungría tiene convenio la UNLaM?'),
(N'¿Con que universidades de Italia tiene convenio la UNLaM?'),
(N'¿Con que universidades de Letonia tiene convenio la UNLaM?'),
(N'¿Con que universidades de México tiene convenio la UNLaM?'),
(N'¿Con que universidades de Paraguay tiene convenio la UNLaM?'),
(N'¿Con que universidades de Perú tiene convenio la UNLaM?'),
(N'¿Con que universidades de República Checa tiene convenio la UNLaM?'),
(N'¿Con que universidades de República Oriental del Uruguay tiene convenio la UNLaM?'),
(N'¿Con que universidades de Turquía tiene convenio la UNLaM?'),
(N'¿Que deportes Indoor se pueden practicar en la UNLaM?'),
(N'¿Que Deportes al Aire Libre se pueden practicar en la UNLaM?'),
(N'¿Que Deportes Acuáticos se pueden practicar en la UNLaM?'),
(N'¿Que Deportes de Combate se pueden practicar en la UNLaM?'),
(N'¿Que deportes se pueden practicar en la Escuelita en la UNLaM?'),
(N'¿Como me anoto a practicar deportes en la UNLaM?'),
(N'¿Que requisitos debo cumplir para practicar en la UNLaM?'),
(N'¿Cual es el correo electrónico de Dirección de alumnos?'),
(N'¿Cual es el teléfono de Dirección de alumnos?');


-- Insert Answers (assuming QuestionId starts at 1 and increments by 1)
INSERT INTO Respuestas VALUES
(1, N'Los títulos expedidos del 2010 en adelante no deben realizar ningún trámite para ser presentados en la Universidad.'),
(1, N'Únicamente aquellos títulos expedidos antes del 2010 deberán ser legalizados en el Ministerio del Interior,'),
(1, N'https://www.argentina.gob.ar/interior'),
(2, N'Conozca la “documentación requerida” y el “procedimiento de inscripción” al Curso de Ingreso.'),
(3, N'No. La inscripción es personal.'),
(4, N'No. Se debe presentar la documentación completa el día de la inscripción en la Dirección de Alumnos.'),
(4, N'En el caso de no tenerla, si quedan fechas disponibles, deberá solicitar un nuevo turno.'),
(5, N'Para inscribirse al Curso de Ingreso de la Universidad, debe presentar el DNI actualizado.'),
(5, N'Si su DNI se encuentra en trámite, excepcionalmente podrá presentar la constancia de DNI en trámite de manera provisoria, comprometiéndose a cumplir con el requisito exigido.'),
(6, N'Para inscribirse al Curso de Ingreso de la Universidad, debe presentar el DNI actualizado.'),
(6, N'Si su DNI se encuentra en trámite, excepcionalmente podrá presentar la constancia de DNI en trámite de manera provisoria, comprometiéndose a cumplir con el requisito exigido.'),
(7, N'El formulario de preinscripción es la ficha que completa el aspirante para comenzar el trámite de inscripción al Curso de Ingreso.'),
(7, N'Este formulario se encontrará disponible en el Sitio de Ingresantes días previos al comienzo de la inscripción y le permitirá sacar un turno para la presentación de la documentación solicitada en la Dirección de Alumnos.'),
(8, N'Si, deberás consultar con la coordinación de tu carrera en el Departamento correspondiente, la posibilidad de tramitar equivalencias.'),
(8, N'En el caso de que corresponda, la Dirección de Alumnos te informará qué documentación presentar en las fechas establecidas en el Calendario Académico.'),
(9, N'Sí. En ese caso el estudiante deberá presentar una constancia general de la escuela que detalle qué materias adeuda y a qué Ciclo lectivo pertenecen, teniendo plazo hasta el 30 de marzo próximo a su inscripción para presentar la Constancia de título en trámite.'),
(9, N'No obstante, si aprobás el Curso de Ingreso y no finalizaste el Ciclo Secundario, se dará por desestimado el mismo.'),
(10, N'Sí. La Universidad ofrece un Taller de Orientación Vocacional gratuito a cargo de la Dirección de Pedagogía Universitaria.'),
(10, N'Para obtener más información, comunicarse o dirigirse al mencionado sector.'),
(11, N'Quienes tengan los tres mejores promedios de todo el Ciclo secundario de cada modalidad que tenga el establecimiento educativo, con un mínimo de ocho puntos de promedio general, quedarán eximidos de la realización de los exámenes del Curso de Ingreso.'),
(11, N'No obstante, obligatoriamente deberán cumplimentar con el 75% de asistencia en cada asignatura y asistir al menos a uno de los tres exámenes, en alguna de las dos instancias del Curso de Ingreso.'),
(11, N'Este beneficio solo es válido para aquellos que hayan finalizado sus estudios secundarios el Ciclo lectivo vigente. Esta modalidad de ingreso no tiene alcance para las carreras de Medicina, Arquitectura, Odontología y la Tec. en Asistencia Odontológica, y, en el caso de la Licenciatura o Profesorado en Educación Física, además de cumplir con el requisito de asistencia, los interesados deberán aprobar con una nota mínima de 7 puntos las pruebas físicas de la asignatura Fundamentos de la Educación Física, sin excepción.'),
(12, N'No. Los graduados de cualquier carrera universitaria de grado y no menor a cuatro años, quedarán exentos de realizar el Curso de Ingreso.'),
(12, N'En el caso de optar por las carreras del Departamento de Ciencias de La Salud, Arquitectura o la Licenciatura/ Profesorado en Educación Física, informarse sobre los requisitos específicos de las mismas.'),
(13, N'No. El Curso de Ingreso es de carácter presencial.'),
(14, N'Se deberá contar con el 75% de asistencia en cada una de las asignaturas del Curso de Ingreso.'),
(15, N'Sí. Se puede realizar en la Dirección de Alumnos presentando una constancia/ nota formal que acredite el motivo de la solicitud.'),
(15, N'La misma quedará sujeta a la verificación de la disponibilidad y tiempos administrativos.'),
(16, N'No. La segunda instancia del Curso de Ingreso no permite inscribirse a las carreras de Medicina, Tec. en Asistencia Odontológica, Odontología y Arquitectura, ya que el ingreso a las mismas consta de una cuarta asignatura a cursar en el verano.'),
(16, N'El resto de las carreras de grado que oferta la Universidad pueden cursarse tanto en la primera, como en la segunda instancia.'),
(16, N'No obstante, se recomienda la inscripción a la segunda instancia para recursantes o reingresantes.'),
(17, N'No. El examen se rinde en un aula designada por la Universidad a través del Sitio de Ingresantes días previos a la fecha de examen.'),
(18, N'El estudiante tiene 90 minutos para desarrollar el examen.'),
(19, N'Sí. El DNI actualizado y original, sin excepción.'),
(20, N'No. En ninguna circunstancia se puede realizar el cambio del aula asignada por la Universidad.'),
(21, N'No. Las fechas de los exámenes son inamovibles.'),
(22, N'La constancia de asistencia a examen acredita tu presencia en un examen.'),
(22, N'Se encuentra en el manual del Curso de Ingreso o se puede descargar desde el Sitio de Ingresantes.'),
(22, N'La misma tendrá validez si es firmada por el docente el día del examen y luego sellada por la Dirección de Alumnos.'),
(23, N'Technische Hochschule Brandenburg'),
(24, N'Universitat Innsbruck'),
(25, N'Thomas More University'),
(26, N'University Of Mostar'),
(27, N'Universidad De Sao Pablo (Usp)'),
(27, N'Universidade Federal Do Tocantins'),
(27, N'Universidade Federal De Juiz De Fora - Ufjf'),
(27, N'Universidad Federal De Sao Carlos'),
(28, N'University Of British Columbia'),
(29, N'Universidad De San Buenaventura (Sede Bogota)'),
(29, N'Universidad Del Cauca'),
(29, N'Universidad Santo Tomas Bucaramanga'),
(29, N'Fundacion Universitaria De Popayan'),
(29, N'Fundacion Universitaria Del Area Andina'),
(30, N'Universidad Central De Costa Rica (Uc)'),
(31, N'Universidad De Zagreb'),
(31, N'University Of Split'),
(32, N'Instituto Tecnológico San Antonio'),
(32, N'Universidad Técnica De Ambato (Uta)'),
(33, N'Universidad De El Salvador (Ues)'),
(34, N'Pavol Jozef Šafárik University In Košice'),
(35, N'Universidad De Santiago De Compostela'),
(35, N'Universidad De Zaragoza'),
(35, N'Universidad De La Coruña'),
(35, N'Universidad Rovira I Virgili'),
(35, N'Universidad De Huelva'),
(35, N'Universidad De Castilla - La Mancha'),
(35, N'Universidad De Almería'),
(35, N'Universidad Pablo De Olavide'),
(36, N'Emory College'),
(37, N'Lovely Professional University (Lpu)'),
(37, N'O. P. Jindal Global University'),
(38, N'L''universite Lumiere Lyon 2'),
(39, N'Óbuda University'),
(40, N'Universidad Magna Da Graecia De Catanzaro'),
(40, N'Universita Degli Studi Di Bari Aldo Moro'),
(40, N'Universita Degli Studi Di Roma Tor Vergata'),
(40, N'Universita Di Camerino'),
(41, N'Riga Technical University'),
(42, N'Universidad Nacional Autónoma De México'),
(43, N'Universidad Nihon Gakko'),
(44, N'Universidad Autónoma De Ica'),
(44, N'Universidad Maria Auxiliadora (Lima - Perú)'),
(44, N'Universidad Catolica De Santa Maria (Arequipa)'),
(44, N'UNIVERSIDAD CONTINENTAL'),
(45, N'Palacky University Olomouc'),
(46, N'Universidad De La Republica'),
(47, N'Istanbul Aydin University'),
(47, N'Zonguldak Bülent Ecevit University'),
(47, N'Istanbul Kültür University'),
(47, N'Canakkale Onsekiz Mart University'),
(48, N'Basquetbol'),
(48, N'Futsal'),
(48, N'Handball'),
(48, N'Gimnasio y Musculación'),
(48, N'Gimnasia Artística'),
(48, N'Spinning'),
(48, N'Voley'),
(48, N'Zumba'),
(49, N'Atletismo'),
(49, N'Fútbol 11'),
(49, N'Hockey'),
(49, N'Rugby'),
(49, N'Softbol'),
(50, N'Natación.'),
(50, N'Natación (Tercera Edad)'),
(50, N'Aqua Zumba y Aqua Gym.'),
(51, N'Boxeo'),
(51, N'Judo'),
(51, N'Taekwondo'),
(52, N'Atletismo'),
(52, N'Basquetbol'),
(52, N'Gimnasia Artística'),
(52, N'Hockey'),
(52, N'Taekwondo'),
(52, N'Judo'),
(52, N'Voley'),
(53, N'Ingresando a:'),
(53, N'https://deportes.unlam.edu.ar/'),
(54, N'Presentar una Ficha Médica del presente ciclo lectivo'),
(55, N'alumnos@unlam.edu.ar'),
(56, N'4480-8900 interno 8866.');