apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-telegrambot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-telegrambot
  template:
    metadata:
      labels:
        app: microservicio-telegrambot
    spec:
      containers:
      - name: microservicio-telegrambot
        image: microservicio-telegrambot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-telegrambot-service
spec:
  type: ClusterIP
  selector:
    app: microservicio-telegrambot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80