apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-cohere
  namespace: chatbot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-cohere
  template:
    metadata:
      labels:
        app: microservicio-cohere
    spec:
      containers:
      - name: microservicio-cohere
        image: microservicio-cohere:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-cohere-service
  namespace: chatbot-dev
spec:
  type: ClusterIP
  selector:
    app: microservicio-cohere
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

